language: php

php:
  - 5.3
  - 5.4
env:
  - SYMFONY_VERSION="2.1.x-dev"
  - SYMFONY_VERSION="2.2.x-dev"

before_script:
    - curl -s http://getcomposer.org/installer | php
    - composer require symfony/framework-bundle:${SYMFONY_VERSION}
    - composer require symfony/twig-bundle:${SYMFONY_VERSION}
    - php composer.phar install --dev